version: '3.2'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ktor_db
    image: postgres
    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d course" ]
      interval: 1s